export const SAMPLE_ORDERS = [
  {
    id: 'ORD-A1B2C',
    trackingId: 'TRK-M5N6P7',
    title: 'Toyota Fleet - 10 Vehicles',
    customer: 'Toyota India Ltd',
    vin: 'JTMZF33V285021001',
    priority: 'High',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    column: 'Pending',
    assignee: null,
    tags: ['Fleet', 'GPS'],
    history: [
      {
        id: 'h1',
        action: 'Order Created',
        from: null,
        to: 'Pending',
        timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
        user: { name: 'System', phone: '—', role: '' },
        note: 'Order auto-created from portal',
      },
    ],
  },
  {
    id: 'ORD-D4E5F',
    trackingId: 'TRK-Q8R9S0',
    title: 'Mahindra XUV 3OO Units',
    customer: 'Mahindra & Mahindra',
    vin: 'MA1FC2GF1P3001234',
    priority: 'Medium',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    column: 'In Process',
    assignee: 'Rohan Sharma',
    tags: ['SUV'],
    history: [
      {
        id: 'h2',
        action: 'Order Created',
        from: null,
        to: 'Pending',
        timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
        user: { name: 'System', phone: '—', role: '' },
        note: 'Order auto-created from portal',
      },
      {
        id: 'h3',
        action: 'Status Changed',
        from: 'Pending',
        to: 'In Process',
        timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
        user: { name: 'Rohan Sharma', phone: '9876543210', role: 'Logistics Manager' },
        note: 'Documents verified, processing started',
      },
    ],
  },
  {
    id: 'ORD-G7H8I',
    trackingId: 'TRK-T1U2V3',
    title: 'Tata Nexon Batch 5',
    customer: 'Tata Motors',
    vin: 'MAT612187P1000456',
    priority: 'Low',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    column: 'Completed',
    assignee: 'Priya Nair',
    tags: ['EV'],
    history: [
      {
        id: 'h4',
        action: 'Order Created',
        from: null,
        to: 'Pending',
        timestamp: new Date(Date.now() - 86400000 * 10).toISOString(),
        user: { name: 'System', phone: '—', role: '' },
        note: 'Order auto-created from portal',
      },
      {
        id: 'h5',
        action: 'Status Changed',
        from: 'Pending',
        to: 'In Process',
        timestamp: new Date(Date.now() - 86400000 * 7).toISOString(),
        user: { name: 'Priya Nair', phone: '9123456780', role: 'Delivery Lead' },
        note: 'Shipment dispatched',
      },
      {
        id: 'h6',
        action: 'Status Changed',
        from: 'In Process',
        to: 'Completed',
        timestamp: new Date(Date.now() - 86400000 * 1).toISOString(),
        user: { name: 'Priya Nair', phone: '9123456780', role: 'Delivery Lead' },
        note: 'All units delivered and verified',
      },
    ],
  },
];
